### PR TITLE
:bug: Fix: Handle empty chart directory correctly

### LINKED ISSUE #288: cso tries to helm template the root of the container if the computed chart name does not match the charts name
/kind bug

**What steps did you take and what happened:**
Created a new cluster-stack from scratch, but added a wrong chart name to the Chart.yaml file in the cluster-class directory.

This lead to the following error message in the cso-logs:

```
walk.go:74: found symbolic link in path: /bin/arch resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ash resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/base64 resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/bbconfig resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/cat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/chattr resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/chgrp resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/chmod resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/chown resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/cp resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/date resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/dd resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/df resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/dmesg resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/dnsdomainname resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/dumpkmap resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/echo resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ed resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/egrep resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/false resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/fatattr resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/fdflush resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/fgrep resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/fsync resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/getopt resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/grep resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/gunzip resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/gzip resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/hostname resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ionice resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/iostat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ipcalc resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/kbd_mode resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/kill resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/link resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/linux32 resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/linux64 resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ln resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/login resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ls resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/lsattr resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/lzop resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/makemime resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mkdir resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mknod resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mktemp resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/more resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mount resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mountpoint resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mpstat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/mv resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/netstat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/nice resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/pidof resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ping resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ping6 resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/pipe_progress resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/printenv resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/ps resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/pwd resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/reformime resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/rev resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/rm resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/rmdir resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/run-parts resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/sed resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/setpriv resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/setserial resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/sh resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/sleep resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/stat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/stty resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/su resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/sync resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/tar resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/touch resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/true resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/umount resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/uname resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/usleep resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/watch resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /bin/zcat resolves to /bin/busybox. Contents of linked file included and used
walk.go:74: found symbolic link in path: /dev/core resolves to /proc/kcore. Contents of linked file included and used
Error: cannot load irregular file /dev/core as it has file mode type bits set
{"level":"ERROR","time":"2025-04-14T15:10:03.096Z","file":"controller/controller.go:324","message":"Reconciler error","controller":"clusterstackrelease","controllerGroup":"clusterstack.x-k8s.io","controllerKind":"ClusterStackRelease","ClusterStackRelease":{"name":"docker-example-1-32-v0-sha-uxh53fj","namespace":"default"},"namespace":"default","name":"docker-example-1-32-v0-sha-uxh53fj","reconcileID":"36117fc7-467e-4cde-9829-f1a6317784dc","error":"failed to template and apply: failed to template clusterClass helm chart: failed to template clusterClass helm chart: failed to run helm template for \"\": exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222"}
```

**What did you expect to happen:**
An error message is given that the cluster stack cannot be used.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-stack-operator version: v0.1.0-alpha.9
- Kubernetes version: 1.32.2
- OS (e.g. from `/etc/os-release`): n/a

### PR DESCRIPTION
**Pull request by jklippel**
Currently the return of helmChartNamePath is not checked on errors. This means that the CSO tries to helm template the container which leads to cryptic error messages from helm.

This commit adds a check on errors on the call to helmChartNamePath and results in more helpful error messages by helm.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #288 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

The log message after the patch is more helpful:

```
{"level":"ERROR","time":"2025-04-14T15:28:57.491Z","file":"controller/controller.go:324","message":"Reconciler error","controller":"clusterstackrelease","controllerGroup":"clusterstack.x-k8s.io","controllerKind":"ClusterStackRelease","ClusterStackRelease":{"name":"docker-example-1-32-v0-sha-uxh53fj","namespace":"default"},"namespace":"default","name":"docker-example-1-32-v0-sha-uxh53fj","reconcileID":"584d729e-a19f-4dbd-9c1d-5a45df7edc21","error":"failed to template and apply: failed to template clusterClass helm chart: failed to template clusterClass helm chart: helm chart matching the name filter docker-example-1-32-cluster-class-v0-sha.uxh53fj not found in /tmp/downloads/cluster-stacks/docker-example-1-32-v0-sha-uxh53fj","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/jakl/GolandProjects/cluster-stack-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222"}
{"level":"INFO","time":"2025-04-14T15:30:13.992Z","file":"fake/client.go:58","message":"WARNING: called DownloadReleaseAssets of fake assets client","controller":"clusterstackrelease","controllerGroup":"clusterstack.x-k8s.io","controllerKind":"ClusterStackRelease","ClusterStackRelease":{"name":"docker-ferrol-1-27-v2","namespace":"cluster"},"namespace":"cluster","name":"docker-ferrol-1-27-v2","reconcileID":"24134593-9a09-4a19-b8dd-0b5f92e09ee6"}
```

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — COMMENTED** [review]
Thanks a lot for the PR!

We currently have a function CheckHelmCharts that should take care of this. I believe that we forgot to update it for the case of multi-stage cluster addons. I think the proper way of handling this would be to update that function in a way that it does its job. 

Can you maybe look into this?

**Comment by chess-knight** [comment]
> We currently have a function CheckHelmCharts that should take care of this. I believe that we forgot to update it for the case of multi-stage cluster addons. I think the proper way of handling this would be to update that function in a way that it does its job.

@janiskemper if I see it correctly, `CheckHelmCharts` is used only in clusteraddon controller right now, but this PR handles errors in the case of clusterclass

**Comment by janiskemper** [comment]
@chess-knight true, my bad. However, my point is still the same. We have this function on purpose to check that everything is correct. Apparently, it doesn't do its job. We should fix that function rather than propagating the error in the other function

**Comment by jklippel** [comment]
@janiskemper I added a call to helmChartNamePath to the validation method. This will show if something is wrong with the name in the helm chart. (Basically it is the same call that raises the error in this case.)

However I would like to keep the  propagation of errors, because it is better to get an error message if it is already available than to drop it on purpose. If there are still some unexpected errors this will definitely help debuging.

**Comment by janiskemper** [comment]
There is the function CheckHelmCharts that has the exact same purpose that you have in mind. Can you plz check how you can add it to that function? I don't mind if you additionally return it with the other function, that should just not be needed anymore

**Comment by jklippel** [comment]
ok, moved the validation call to `CheckHelmCharts()`.
Unfortunately that did not solve the issue as the `CheckHelmCharts()` does not get called prior to the original error.
I added a call to `CheckHelmCharts()` to the `Validate()` method. Now things work as expected.
Is that what you had in mind @janiskemper ?

**Comment by janiskemper** [comment]
alright! Thanks for the info. Then the problem is actually that the function was not called in the clusterstackrelease controller. We have this in the clusteraddon-controller:

```
	// Check for helm charts in the release assets. If they are not present, then something went wrong.
	if err := releaseAsset.CheckHelmCharts(); err != nil {
		msg := fmt.Sprintf("failed to validate helm charts: %s", err.Error())
		conditions.MarkFalse(
			clusterAddon,
			csov1alpha1.ClusterStackReleaseAssetsReadyCondition,
			csov1alpha1.IssueWithReleaseAssetsReason,
			clusterv1.ConditionSeverityError,
			"%s", msg,
		)
		record.Warn(clusterAddon, "ValidateHelmChartFailed", msg)
		return reconcile.Result{}, nil
	}
	```
	
	I think we should add that to respective place in the clusterstackrelease controller. WDYT?

**Comment by janiskemper** [comment]
My point was that we actually don't call the function in the first place in the clusterstackrelease controller. We should do that however. So can you add the above code snippet to the clusterstackrelease controller?

**Comment by jklippel** [comment]
ok, moved to [internal/controller/clusterstackrelease_controller.go:155](https://github.com/SovereignCloudStack/cluster-stack-operator/pull/289/files#diff-d9acc7cb9def2647281a077a964e937ba332b1352093e225a38e4c3fe2f2c405R155)
That indeed seems to be the better place for this.
Thanks for the snippet!

**Review by janiskemper — APPROVED** [review]
LGTM

**Comment by jklippel** [comment]
The test [Test Code / Test Code (pull_request)](https://github.com/SovereignCloudStack/cluster-stack-operator/actions/runs/14518407791/job/40995505912?pr=289) fails as the clusterstack used does not have a cluster-addon-values.yaml.

If this patch is merged then this will no longer be optional.
Would that be correct or should having a cluster-addon-values.yaml stay optional?

File: pkg/release/release.go [hunk 1]
```diff
@@ -159,6 +159,11 @@ func ensureMetadata(downloadPath, metadataFileName string) (Metadata, error) {
 func (r *Release) CheckHelmCharts() error {
 	// check if the cluster class chart is present.
 	clusterClassChartName := r.clusterClassChartName()
+
+	if _, err := r.ClusterClassChartPath(); err != nil {
```
Comment (janiskemper) [inline pkg/release/release.go:163]: isn't this the same as the one below?

Comment (jklippel) [reply pkg/release/release.go]: > isn't this the same as the one below?
yes, indeed; I removed it

Comment (jklippel) [reply pkg/release/release.go]: After some refactoring the tests are green now and everything looks good to go again.

**Comment by jklippel** [comment]
> I think this PR already is an improvement. However, we removed validation around the cluster-addon-values.yaml file. We could add it back by manually checking that the file exists before this line here:
> 
> https://github.com/SovereignCloudStack/cluster-stack-operator/blob/c12de9b8ad05e1a8e3429b9f9b4a54767d26fa95/internal/controller/clusteraddon_controller.go#L242
> 
> WDYT?

I don't see the benifit to be honest, because:

`templateAndApplyClusterAddonHelmChart` https://github.com/SovereignCloudStack/cluster-stack-operator/blob/c12de9b8ad05e1a8e3429b9f9b4a54767d26fa95/internal/controller/clusteraddon_controller.go#L740 calls `buildTemplateFromClusterAddonValues`  which then validates whether the file exists: https://github.com/SovereignCloudStack/cluster-stack-operator/blob/c12de9b8ad05e1a8e3429b9f9b4a54767d26fa95/internal/controller/clusteraddon_controller.go#L1196 So adding another check before line 242 would just be redundant. Or am I missing something?

**Review by janiskemper — APPROVED** [review]
true, I didn't realize and didn't go down so deep. Then LGTM from my side
